---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
spec:
  commonConfiguration:
    replicas: 1
    hostNetwork: false
#    imagePullSecrets:
#    - contrail-nightly
  services:
    cassandras:
    - metadata:
        name: cassandra1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          activate: true
          create: true
        serviceConfiguration:
          images:
            cassandra: cassandra:3.11.4
            init: busybox
          listenAddress: auto
          startRpc: true
          port: 9160
          cqlPort: 9042
          sslStoragePort: 7001
          storagePort: 7000
          jmxLocalPort: 7199
          clusterName: ContrailConfigDB
          maxHeapSize: 1024M
          minHeapSize: 100M