---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
spec:
  commonConfiguration:
    replicas: 1
    hostNetwork: false
    imagePullSecrets:
    - contrail-nightly
  services:
    cassandras:
    - metadata:
        name: cassandra1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          activate: true
          create: true
        serviceConfiguration:
          images:
            cassandra: cassandra:3.11.4
            init: busybox
          listenAddress: auto
          startRpc: true
          port: 9160
          cqlPort: 9042
          sslStoragePort: 7001
          storagePort: 7000
          jmxLocalPort: 7199
          clusterName: ContrailConfigDB
          maxHeapSize: 1024M
          minHeapSize: 100M
    zookeepers:
    - metadata:
        name: zookeeper1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          activate: true
          create: true
        serviceConfiguration:
          images:
            zookeeper: docker.io/zookeeper:3.5.5
            init: busybox
          clientPort: 2181
          electionPort: 3888
          serverPort: 2888
    rabbitmq:
      metadata:
        name: rabbitmq1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          activate: true
          create: true
        serviceConfiguration:
          images:
            rabbitmq: rabbitmq:3.7
            init: busybox
          port: 5673
          erlangCookie: 47EFF3BB-4786-46E0-A5BB-58455B3C2CB4
    config:
      metadata:
        name: config1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          activate: true
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            api: hub.juniper.net/contrail-nightly/contrail-controller-config-api:5.2.0-0.740
            devicemanager: hub.juniper.net/contrail-nightly/contrail-controller-config-devicemgr:5.2.0-0.740
            schematransformer: hub.juniper.net/contrail-nightly/contrail-controller-config-schema:5.2.0-0.740
            servicemonitor: hub.juniper.net/contrail-nightly/contrail-controller-config-svcmonitor:5.2.0-0.740
            analyticsapi: hub.juniper.net/contrail-nightly/contrail-analytics-api:5.2.0-0.740
            collector: hub.juniper.net/contrail-nightly/contrail-analytics-collector:5.2.0-0.740
            redis: hub.juniper.net/contrail-nightly/contrail-external-redis:5.2.0-0.740
            nodemanagerconfig: hub.juniper.net/contrail-nightly/contrail-nodemgr:5.2.0-0.740
            nodemanageranalytics: hub.juniper.net/contrail-nightly/contrail-nodemgr:5.2.0-0.740
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:5.2.0-0.740
            init: busybox
