apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managers.contrail.juniper.net
spec:
  group: contrail.juniper.net
  names:
    kind: Manager
    listKind: ManagerList
    plural: managers
    singular: manager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cassandra:
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
            config:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
            contrailStatusImage:
              type: string
            control:
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
            hostNetwork:
              type: boolean
            kubemanager:
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
            rabbitmq:
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
            size:
              format: int32
              type: integer
            zookeeper:
              properties:
                activate:
                  type: boolean
                configuration:
                  additionalProperties:
                    type: string
                  type: object
                create:
                  type: boolean
                image:
                  type: string
                images:
                  additionalProperties:
                    type: string
                  type: object
                size:
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          properties:
            cassandra:
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
            config:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
            control:
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
            kubemanager:
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
            rabbitmq:
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
            zookeeper:
              properties:
                active:
                  type: boolean
                created:
                  type: boolean
              type: object
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
