apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contrail-manager
  template:
    metadata:
      labels:
        name: contrail-manager
    spec:
      serviceAccountName: contrail-manager
      hostNetwork: true
      containers:
        - name: contrail-manager
          # Replace this with the built image name
          image: docker.io/michaelhenkel/contrail-manager
          command:
          - contrail-manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "contrail-manager"
